# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-14 03:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BmdwField',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_code', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='DataFamily',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('contact', models.CharField(blank=True, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='DictionaryField',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=200, unique=True)),
                ('description_short', models.CharField(max_length=200, verbose_name='Short Description')),
                ('description_long', models.TextField(verbose_name='Long Description')),
                ('field_type', models.CharField(choices=[('N', 'Numeric'), ('A', 'Alphanumeric'), ('S', 'List Single'), ('M', 'List Multiple'), ('D', 'Date'), ('F', 'Free Form')], max_length=1)),
                ('units', models.CharField(blank=True, max_length=200)),
                ('range', models.CharField(blank=True, max_length=200)),
                ('values', models.CharField(blank=True, max_length=200)),
                ('owner_family', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owns', to='wmdadict.DataFamily')),
                ('user_family', models.ManyToManyField(blank=True, related_name='uses', to='wmdadict.DataFamily')),
            ],
        ),
        migrations.CreateModel(
            name='EmdisField',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_code', models.CharField(max_length=50, unique=True)),
                ('field_description', models.CharField(max_length=200)),
                ('field_type', models.CharField(max_length=10)),
                ('field_rule', models.TextField()),
                ('dict_field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wmdadict.DictionaryField', verbose_name='WMDA Dictionary Field')),
            ],
        ),
        migrations.CreateModel(
            name='EmdisMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('description', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='FormFields',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('form_field_name', models.CharField(max_length=200)),
                ('dict_field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wmdadict.DictionaryField')),
            ],
        ),
        migrations.CreateModel(
            name='WmdaForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('form_code', models.CharField(max_length=10, unique=True)),
                ('description', models.CharField(max_length=200)),
                ('fields', models.ManyToManyField(through='wmdadict.FormFields', to='wmdadict.DictionaryField')),
            ],
        ),
        migrations.AddField(
            model_name='formfields',
            name='wmda_form',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wmdadict.WmdaForm'),
        ),
        migrations.AddField(
            model_name='emdisfield',
            name='emdis_messages',
            field=models.ManyToManyField(to='wmdadict.EmdisMessage'),
        ),
        migrations.AddField(
            model_name='bmdwfield',
            name='dict_field',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wmdadict.DictionaryField'),
        ),
    ]
