# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-15 06:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wmdadict', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dictionaryfield',
            old_name='user_family',
            new_name='user_families',
        ),
        migrations.AlterField(
            model_name='bmdwfield',
            name='dict_field',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wmdadict.DictionaryField', verbose_name='WMDA Dictionary Field'),
        ),
        migrations.AlterField(
            model_name='formfields',
            name='dict_field',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wmdadict.DictionaryField', verbose_name='WMDA Dictionary Field'),
        ),
    ]
