# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-16 22:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wmdadict', '0003_auto_20170815_1736'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bmdwfield',
            options={'verbose_name': 'BMDW field'},
        ),
        migrations.AlterModelOptions(
            name='datafamily',
            options={'verbose_name_plural': 'data families'},
        ),
        migrations.AlterModelOptions(
            name='emdisfield',
            options={'verbose_name': 'EMDIS field'},
        ),
        migrations.AlterModelOptions(
            name='emdismessage',
            options={'verbose_name': 'EMDIS message'},
        ),
        migrations.AlterModelOptions(
            name='formfields',
            options={'verbose_name_plural': 'form fields'},
        ),
        migrations.AlterModelOptions(
            name='wmdaform',
            options={'verbose_name': 'WMDA form'},
        ),
    ]
