# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-16 23:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wmdadict', '0004_auto_20170817_0819'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dictionaryfield',
            options={'ordering': ['label']},
        ),
        migrations.AlterField(
            model_name='dictionaryfield',
            name='field_type',
            field=models.CharField(choices=[('N', 'Numeric'), ('A', 'Alphanumeric'), ('S', 'List Single'), ('M', 'List Multiple'), ('D', 'Date'), ('F', 'Free Form'), ('U', 'Undecided')], max_length=1),
        ),
    ]
