# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-17 10:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wmdadict', '0005_auto_20170817_0906'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='emdisfield',
            options={'ordering': ['field_code'], 'verbose_name': 'EMDIS field'},
        ),
        migrations.AlterModelOptions(
            name='emdismessage',
            options={'ordering': ['name'], 'verbose_name': 'EMDIS message'},
        ),
    ]
