# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-22 12:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wmdadict', '0007_auto_20170822_2154'),
    ]

    operations = [
        migrations.RenameField(
            model_name='emdisfield',
            old_name='messages',
            new_name='emdis_messages',
        ),
    ]
