# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-23 08:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wmdadict', '0008_auto_20170822_2212'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='formfields',
            options={'ordering': ('wmda_form', 'order'), 'verbose_name_plural': 'form fields'},
        ),
        migrations.RenameField(
            model_name='bmdwfield',
            old_name='field_code',
            new_name='field_identifier',
        ),
        migrations.AddField(
            model_name='bmdwfield',
            name='comment',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='bmdwfield',
            name='description',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='bmdwfield',
            name='element_type',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='bmdwfield',
            name='length',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='bmdwfield',
            name='required',
            field=models.CharField(blank=True, choices=[('Y', 'Yes'), ('N', 'Required')], max_length=1),
        ),
        migrations.AddField(
            model_name='bmdwfield',
            name='type',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='formfields',
            name='order',
            field=models.PositiveIntegerField(db_index=True, default=1, editable=False),
            preserve_default=False,
        ),
    ]
