# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-23 09:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wmdadict', '0009_auto_20170823_1850'),
    ]

    operations = [
        migrations.AddField(
            model_name='wmdaform',
            name='form_url',
            field=models.URLField(blank=True),
        ),
    ]
