# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-23 11:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wmdadict', '0011_auto_20170823_2155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dictionaryfield',
            name='values',
            field=models.TextField(blank=True, max_length=200),
        ),
    ]
