# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-24 12:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wmdadict', '0012_auto_20170823_2159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bmdwfield',
            name='dict_field',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='wmdadict.DictionaryField', verbose_name='WMDA Dictionary Field'),
        ),
        migrations.AlterField(
            model_name='bmdwfield',
            name='field_identifier',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='bmdwfield',
            name='required',
            field=models.CharField(blank=True, choices=[('Y', 'Yes'), ('N', 'No'), ('D', 'Dependent')], max_length=1),
        ),
    ]
