# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-27 12:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wmdadict', '0013_auto_20170824_2204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emdisfield',
            name='field_description',
            field=models.CharField(max_length=500),
        ),
    ]
