# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-27 12:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wmdadict', '0014_auto_20170827_2230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bmdwfield',
            name='description',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
