# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-27 12:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wmdadict', '0015_auto_20170827_2232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bmdwfield',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
