# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-30 09:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wmdadict', '0016_auto_20170827_2234'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmdisFieldType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('letter_code', models.CharField(max_length=1, unique=True)),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'EMDIS field type',
                'ordering': ['letter_code'],
            },
        ),
        migrations.AddField(
            model_name='emdisfield',
            name='field_length',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='emdisfield',
            name='emdis_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='wmdadict.EmdisFieldType', verbose_name='field type'),
        ),
    ]
