# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-30 11:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wmdadict', '0017_auto_20170830_1920'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emdisfield',
            name='field_type',
        ),
        migrations.AlterField(
            model_name='emdisfield',
            name='emdis_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wmdadict.EmdisFieldType', verbose_name='field type'),
        ),
        migrations.AlterField(
            model_name='emdisfield',
            name='field_length',
            field=models.PositiveIntegerField(),
        ),
    ]
