# Generated by Django 2.0.dev20170903160644 on 2017-09-06 09:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wmdadict', '0018_auto_20170830_2143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dictionaryfield',
            name='owner_family',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owns', to='wmdadict.DataFamily'),
        ),
        migrations.AlterField(
            model_name='dictionaryfield',
            name='user_families',
            field=models.ManyToManyField(related_name='uses', to='wmdadict.DataFamily'),
        ),
        migrations.AlterField(
            model_name='emdisfield',
            name='dict_field',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='wmdadict.DictionaryField', verbose_name='WMDA Dictionary Field'),
        ),
        migrations.AlterField(
            model_name='emdisfield',
            name='emdis_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='wmdadict.EmdisFieldType', verbose_name='field type'),
        ),
        migrations.AlterField(
            model_name='emdissemantics',
            name='emdis_field',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='wmdadict.EmdisField'),
        ),
        migrations.AlterField(
            model_name='emdissemantics',
            name='emdis_message',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='wmdadict.EmdisMessage'),
        ),
        migrations.AlterField(
            model_name='formfields',
            name='dict_field',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='wmdadict.DictionaryField', verbose_name='WMDA Dictionary Field'),
        ),
        migrations.AlterField(
            model_name='formfields',
            name='wmda_form',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='wmdadict.WmdaForm'),
        ),
    ]
