# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-13 12:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wmdadict', '0019_auto_20170906_1908'),
    ]

    operations = [
        migrations.CreateModel(
            name='DictionaryFieldType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('letter_code', models.CharField(max_length=1, unique=True)),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['letter_code'],
            },
        ),
        migrations.CreateModel(
            name='RequiredFieldType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('letter_code', models.CharField(max_length=1, unique=True)),
                ('emdis_label', models.CharField(max_length=30)),
                ('bmdw_label', models.CharField(max_length=30)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['letter_code'],
            },
        ),
        migrations.AddField(
            model_name='emdissemantics',
            name='post_text',
            field=models.TextField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='emdissemantics',
            name='pre_text',
            field=models.TextField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='bmdwfield',
            name='required_new',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='wmdadict.RequiredFieldType'),
        ),
        migrations.AddField(
            model_name='dictionaryfield',
            name='field_type_new',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='wmdadict.DictionaryFieldType'),
        ),
        migrations.AddField(
            model_name='emdissemantics',
            name='required_new',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='wmdadict.RequiredFieldType'),
        ),
    ]
