# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-14 00:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wmdadict', '0020_auto_20170913_2248'),
    ]

    operations = [
        migrations.CreateModel(
            name='BmdwElementType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'BMDW element type',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='BmdwFieldType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'BMDW field type',
                'ordering': ['title'],
            },
        ),
        migrations.AlterField(
            model_name='dictionaryfield',
            name='user_families',
            field=models.ManyToManyField(blank=True, null=True, related_name='uses', to='wmdadict.DataFamily'),
        ),
        migrations.AddField(
            model_name='bmdwfield',
            name='element_type_new',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='wmdadict.BmdwElementType'),
        ),
        migrations.AddField(
            model_name='bmdwfield',
            name='type_new',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='wmdadict.BmdwFieldType'),
        ),
    ]
