# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-14 05:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wmdadict', '0022_auto_20170914_1526'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bmdwfield',
            old_name='element_type',
            new_name='element_type_old',
        ),
        migrations.RenameField(
            model_name='bmdwfield',
            old_name='required',
            new_name='required_old',
        ),
        migrations.RenameField(
            model_name='bmdwfield',
            old_name='type',
            new_name='type_old',
        ),
        migrations.RenameField(
            model_name='emdissemantics',
            old_name='required',
            new_name='required_old',
        ),
    ]
