# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-14 08:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wmdadict', '0024_auto_20170914_1536'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dictionaryfieldtype',
            options={'ordering': ['title']},
        ),
        migrations.RemoveField(
            model_name='dictionaryfieldtype',
            name='letter_code',
        ),
        migrations.RemoveField(
            model_name='emdissemantics',
            name='post_text',
        ),
        migrations.RemoveField(
            model_name='emdissemantics',
            name='pre_text',
        ),
        migrations.AddField(
            model_name='emdismessage',
            name='post_text',
            field=models.TextField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='emdismessage',
            name='pre_text',
            field=models.TextField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='formfields',
            name='form_field_current_name',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
