# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-15 10:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wmdadict', '0025_auto_20170914_1846'),
    ]

    operations = [
        migrations.AddField(
            model_name='dictionaryfieldtype',
            name='has_range',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dictionaryfieldtype',
            name='has_units',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dictionaryfieldtype',
            name='has_values',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
