# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-15 12:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wmdadict', '0026_auto_20170915_2018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emdismessage',
            name='post_text',
            field=models.TextField(blank=True, max_length=10000),
        ),
        migrations.AlterField(
            model_name='emdismessage',
            name='pre_text',
            field=models.TextField(blank=True, max_length=10000),
        ),
    ]
