# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-17 10:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wmdadict', '0027_auto_20170915_2241'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bmdwfield',
            options={'ordering': ('element_type', 'field_identifier'), 'verbose_name': 'BMDW field'},
        ),
        migrations.AddField(
            model_name='requiredfieldtype',
            name='display_strong',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
