# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-17 10:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wmdadict', '0028_auto_20170917_2003'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='requiredfieldtype',
            options={},
        ),
        migrations.RemoveField(
            model_name='dictionaryfield',
            name='field_type_old',
        ),
        migrations.RemoveField(
            model_name='requiredfieldtype',
            name='letter_code',
        ),
        migrations.AlterField(
            model_name='dictionaryfield',
            name='field_type',
            field=models.ForeignKey(default=999, on_delete=django.db.models.deletion.PROTECT, to='wmdadict.DictionaryFieldType'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='dictionaryfield',
            name='owner_family',
            field=models.ForeignKey(default=999, on_delete=django.db.models.deletion.PROTECT, related_name='owns', to='wmdadict.DataFamily'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='dictionaryfield',
            name='user_families',
            field=models.ManyToManyField(blank=True, related_name='uses', to='wmdadict.DataFamily'),
        ),
    ]
