# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-17 11:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wmdadict', '0030_auto_20170917_2104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bmdwfield',
            name='element_type',
            field=models.ForeignKey(default=999, on_delete=django.db.models.deletion.PROTECT, to='wmdadict.BmdwElementType'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bmdwfield',
            name='required',
            field=models.ForeignKey(default=999, on_delete=django.db.models.deletion.PROTECT, to='wmdadict.RequiredFieldType'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bmdwfield',
            name='type',
            field=models.ForeignKey(default=999, on_delete=django.db.models.deletion.PROTECT, to='wmdadict.BmdwFieldType'),
            preserve_default=False,
        ),
    ]
