---
title: "WMDA EMDIS Mapping"
output: html_notebook
---


```{r setup}
library(tidyverse)
library(readxl)
library(stringr)

```


```{r wmda_2_emdis}
wmda_emdis_wide <-
  read_excel(
    "~/develop/python-projects/wmdasite/docs/WMDA-Data-Dictionary-JS-AGM-2017-08-17-v3.xlsx",
    sheet = "W-E-Map-Wide"
  )

n_vars <- wmda_emdis_wide$'EMDIS Field Codes' %>% 
  str_split(",") %>%
  lapply(function(z) length(z)) %>% 
  unlist() %>% 
  max()


wmda_emdis <- wmda_emdis_wide %>%
  rename(
    id = id,
    label = Label,
    emdis = 'EMDIS Field Codes') %>%
  separate(emdis, into = paste0("emdis_", 1:n_vars), sep = ",", extra = "merge", fill = "right") %>%
  gather(emdis_key, emdis_field, starts_with("emdis_"), na.rm = TRUE) %>%
  mutate(emdis_field = trimws(emdis_field)) %>%
  select(emdis_field, id, label) %>%
  arrange(emdis_field)

write_csv(wmda_emdis, "~/develop/python-projects/wmdasite/docs/wmda-emdis.csv")

```

```{r user_map}
user_wide <- 
  read_excel(
    "~/develop/python-projects/wmdasite/data/WMDA-Data-Dictionary-JS-AGM-2017-08-17-v3.xlsx",
    sheet = "User-Map-Wide"
  )

n_user_vars <- user_wide$user %>% 
  str_split(",") %>%
  lapply(function(z) length(z)) %>% 
  unlist() %>% 
  max()

user_families <- user_wide %>%
  separate(user, into = paste0("usr_", 1:n_user_vars), sep = ",", extra = "merge", fill = "right") %>%
  gather(user_key, user, starts_with("usr_"), na.rm = TRUE) %>%
  mutate(user = trimws(user)) %>%
  select(user, id, label) %>%
  arrange(user)

write_csv(user_families, "~/develop/python-projects/wmdasite/docs/user_families.csv")

```

```{r forms_map}
forms_wide <- 
  read_excel(
    "~/develop/python-projects/wmdasite/data/WMDA-Data-Dictionary-JS-AGM-2017-08-17-v3.xlsx",
    sheet = "Form-Map-Wide"
  )

n_forms_vars <- forms_wide$forms %>% 
  str_split(",") %>%
  lapply(function(z) length(z)) %>% 
  unlist() %>% 
  max()

forms_long <- forms_wide %>%
  separate(forms, into = paste0("form_", 1:n_forms_vars), sep = ",", extra = "merge", fill = "right") %>%
  gather(forms_key, form, starts_with("form_"), na.rm = TRUE) %>%
  mutate(form = trimws(form)) %>%
  select(form, id, label) %>%
  arrange(form)

write_csv(forms_long, "~/develop/python-projects/wmdasite/data/forms_long.csv")

```


```{r emdis_field_2_msg}
emdis_msg_wide <- 
  read_excel(
    "~/develop/python-projects/wmdasite/docs/WMDA-Data-Dictionary-JS-AGM-2017-08-17-v3.xlsx",
    sheet = "EFM-Map-Wide"
  )

n_msg_vars <- emdis_msg_wide$messages %>% 
  str_split(",") %>%
  lapply(function(z) length(z)) %>% 
  unlist() %>% 
  max()

field_messages <- emdis_msg_wide %>%
  separate(messages, into = paste0("msg_", 1:n_msg_vars), sep = ",", extra = "merge", fill = "right") %>%
  gather(msg_key, message, starts_with("msg_"), na.rm = TRUE) %>%
  mutate(message = trimws(message)) %>%
  select(message, id, field_code) %>%
  arrange(message)

write_csv(field_messages, "~/develop/python-projects/wmdasite/docs/field_messages.csv")

```

```{r distint_msgs}

distinct_msg <- field_messages %>%
  distinct(message)

write_csv(distinct_msg, "~/develop/python-projects/wmdasite/docs/messages.csv")

distinct_msg %>%
  pull(message) %>%
  paste0(collapse = ", ")


```